## Iterators And Generators

#### Iterators:
- iterator is an object that contains a number of elements. Iterator implements two methods called “_iter_” and “_next_”. 

In [7]:
srit=iter("python")
print(next(srit))
print(next(srit))
print(next(srit))
print(next(srit))
print(next(srit))
print(next(srit))

p
y
t
h
o
n


In [5]:
xy = ["c","java","python"]
res = iter(xy)
print(next(res))
print(next(res))

c
java


In [4]:
a = iter(("apple","mango","orange"))
print(next(a))
print(next(a))

apple
mango


In [6]:
s=iter(["SRIT","ATP"])
print(next(s))

SRIT


## Generators 
 -  Generator is a function that returns iterators or objects. Generators uses “yield” instead of “return”.

In [7]:
def genFunction():
    yield 1
    yield 2
    yield 3
    
for value in genFunction():
    print(value)

1
2
3


In [8]:
# Function to print square of each number until it reaches the upper bound range using Generators function.
def gen():
    n=2
    while True:
        n**=2
        yield n
ls=[]
a=gen()
for i in range(5):
    ls.append(next(a))
print(ls)

[4, 16, 256, 65536, 4294967296]


## Python Libraries
 - Numpy
 - Pandas
 - Matplotlib

### Numpy
   - Numerical python is used to create multidimensional arrays for fast operations.
#### For installing numpy
- pip3 install -U numpy  

In [14]:
# Creating 1D using numPy.
import numpy as np
array_1d = np.array([1,2,3,'srit'])
print(array_1d)

['1' '2' '3' 'srit']


In [15]:
# Creating 2D array using numPy.
import numpy as np
array_2d = np.array([[1,2,3],['ap','sdc']])
print(array_2d)

[list([1, 2, 3]) list(['ap', 'sdc'])]


In [16]:
# Program to print the given List into an Array using numpy.
import numpy as np
li=[2,3,'srit',10.5]
a = np.array(li)
print(a)

['2' '3' 'srit' '10.5']


In [17]:
import numpy as np
ls=[[5,'srit',10.5],[100,200]]
a = np.array(ls)
print(a)

[list([5, 'srit', 10.5]) list([100, 200])]


In [20]:
# print 1D array between 1 to 15.
import numpy as np
a=np.arange(16)
print(a)
  

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [26]:
# print 1000 numbers in a 1D array
import numpy as np
x=np.arange(50).reshape(5,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [27]:
import numpy as np
x=np.arange(20).reshape(5,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### Pandas
 - Derived from “PANel Data – an Econometrics from Multidimensional data”. 
 - It is an open source python library that produces high-performance data manipulation and analysis tool.
##### For installing pandas
 - pip3 install -U pandas